# -*- coding: utf-8 -*-
"""download_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9xf_b9C8LGf_wDJQ7HTI5CvVoRYyIxC
"""

import logging

import torchvision
import torchvision.transforms as transforms


logging.basicConfig(
    filename="logs/pipeline.log",
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s"
)


def download_data():

    transform = transforms.ToTensor()

    torchvision.datasets.CIFAR10(
        root="data/raw",
        train=True,
        download=True,
        transform=transform
    )

    torchvision.datasets.CIFAR10(
        root="data/raw",
        train=False,
        download=True,
        transform=transform
    )

    logging.info("Dataset downloaded")


if __name__ == "__main__":
    download_data()