# -*- coding: utf-8 -*-
"""evaluate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9xf_b9C8LGf_wDJQ7HTI5CvVoRYyIxC
"""

import json
import yaml

import torch

import torchvision
import torchvision.transforms as transforms

from torch.utils.data import DataLoader

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

from model import SimpleCNN


def load_params():

    with open("params.yaml", "r") as file:
        return yaml.safe_load(file)


def evaluate():

    params = load_params()

    transform = transforms.Compose([
        transforms.ToTensor()
    ])

    test_dataset = torchvision.datasets.CIFAR10(
        root="data/raw",
        train=False,
        download=False,
        transform=transform
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=params["data"]["batch_size"]
    )

    model = SimpleCNN(
        params["model"]["num_classes"]
    )

    model.load_state_dict(
        torch.load("artifacts/best_model.pth")
    )

    model.eval()

    y_true = []
    y_pred = []

    with torch.no_grad():

        for images, labels in test_loader:

            outputs = model(images)

            _, preds = torch.max(outputs, 1)

            y_true.extend(labels.numpy())
            y_pred.extend(preds.numpy())

    metrics = {

        "accuracy": accuracy_score(
            y_true,
            y_pred
        ),

        "precision": precision_score(
            y_true,
            y_pred,
            average="macro"
        ),

        "recall": recall_score(
            y_true,
            y_pred,
            average="macro"
        ),

        "f1_score": f1_score(
            y_true,
            y_pred,
            average="macro"
        )
    }

    with open(
        "metrics/metrics.json",
        "w"
    ) as file:

        json.dump(
            metrics,
            file,
            indent=4
        )

    print(metrics)


if __name__ == "__main__":
    evaluate()