# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9xf_b9C8LGf_wDJQ7HTI5CvVoRYyIxC
"""

import logging
import yaml

import torch
import torch.nn as nn

import torchvision
import torchvision.transforms as transforms

import mlflow
import mlflow.pytorch

from torch.utils.data import (
    DataLoader,
    Subset,
    ConcatDataset
)

from model import SimpleCNN


logging.basicConfig(
    filename="logs/pipeline.log",
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s"
)


def load_params():

    with open("params.yaml", "r") as file:
        return yaml.safe_load(file)


def prepare_data(params):

    transform_train = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ToTensor()
    ])

    full_train_dataset = torchvision.datasets.CIFAR10(
        root="data/raw",
        train=True,
        download=False,
        transform=transform_train
    )

    num_chunks = params["data"]["num_chunks"]

    dataset_size = len(full_train_dataset)

    chunk_size = dataset_size // num_chunks

    chunks = []

    for i in range(num_chunks):

        start_idx = i * chunk_size

        if i == num_chunks - 1:
            end_idx = dataset_size
        else:
            end_idx = (i + 1) * chunk_size

        indices = list(range(start_idx, end_idx))

        chunk = Subset(full_train_dataset, indices)

        chunks.append(chunk)

    train_chunks = [
        chunks[i]
        for i in params["data"]["train_chunks"]
    ]

    val_chunks = [
        chunks[i]
        for i in params["data"]["val_chunks"]
    ]

    train_dataset = ConcatDataset(train_chunks)
    val_dataset = ConcatDataset(val_chunks)

    train_loader = DataLoader(
        train_dataset,
        batch_size=params["data"]["batch_size"],
        shuffle=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=params["data"]["batch_size"]
    )

    return train_loader, val_loader

mlflow.set_experiment("CIFAR10_MLOPS")

def train():

    params = load_params()

    train_loader, val_loader = prepare_data(params)

    model = SimpleCNN(
        params["model"]["num_classes"]
    )

    criterion = nn.CrossEntropyLoss()

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=params["training"]["learning_rate"]
    )

    best_val_loss = float("inf")

    logging.info("Training started")

    # MLflow run
    with mlflow.start_run(
        run_name="Stage2 - CNN Training"
    ):

        # log params
        mlflow.log_params({
            "batch_size": params["data"]["batch_size"],
            "epochs": params["training"]["epochs"],
            "learning_rate": params["training"]["learning_rate"],
            "num_chunks": params["data"]["num_chunks"]
        })

        for epoch in range(params["training"]["epochs"]):

            model.train()

            train_loss = 0

            for images, labels in train_loader:

                optimizer.zero_grad()

                outputs = model(images)

                loss = criterion(outputs, labels)

                loss.backward()

                optimizer.step()

                train_loss += loss.item()

            logging.info(
                f"Epoch {epoch+1}, Loss {train_loss}"
            )

            print(f"Epoch {epoch+1}, Loss {train_loss}")

            # 🔥 MLflow metrics
            mlflow.log_metric(
                "train_loss",
                train_loss,
                step=epoch
            )

        torch.save(
            model.state_dict(),
            "artifacts/best_model.pth"
        )

        # log model
        mlflow.pytorch.log_model(
            model,
            "model"
        )

        # log config
        mlflow.log_dict(
            params,
            "params.json"
        )

        logging.info("Model saved")


if __name__ == "__main__":
    train()
